apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.activeVersion }}
  labels:
    app: nodejs
    version: {{ .Values.activeVersion }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nodejs
      version: {{ .Values.activeVersion }}
  template:
    metadata:
      labels:
        app: nodejs
        version: {{ .Values.activeVersion }}
    spec:
      containers:
      - name: nodejs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
