apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejs-blue
  labels:
    app: nodejs-blue
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nodejs-blue
  template:
    metadata:
      labels:
        app: nodejs-blue
    spec:
      containers:
        - name: nodejs
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
