apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.version }}
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: {{ .Values.version }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.containerPort }}

