apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  selector:
    app: nodejs
    version: {{ .Values.activeVersion }}
  ports:
  - port: 3000
    targetPort: 3000
