apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.activeApp }}
  ports:
    - port: 3000
      targetPort: 3000
